import itertools
import unittest
from fractions import Fraction

from jordan_bootstrap.composite import (
    associates,
    canonical_associator_witness,
    composite_wall_census,
    elementary,
)
from jordan_bootstrap.octonion import E, octonion


class GateO03CompositeWall(unittest.TestCase):
    """Octonion premise, Gate O03: no consistent composite octonionic system.

    Composing observables needs an associative envelope (special Jordan algebra).
    Octonionic 3x3 matrix multiplication is non-associative, so no envelope
    exists: octonionic quantum mechanics is a single-system probability calculus
    with no tensor product. By Artin's theorem any two octonions still associate,
    so the wall appears precisely at h_3(O) -- three independent directions.
    """

    @classmethod
    def setUpClass(cls) -> None:
        cls.census = composite_wall_census()

    def test_octonionic_matrix_product_is_non_associative(self) -> None:
        self.assertEqual(self.census.octonionic_checks, 3)
        self.assertEqual(self.census.octonionic_non_associative, 3)

    def test_complex_realization_associates(self) -> None:
        # h_n(C) is special (associative envelope M_n(C)): composition works.
        self.assertEqual(self.census.complex_checks, 2)
        self.assertEqual(self.census.complex_non_associative, 0)

    def test_quaternionic_realization_associates(self) -> None:
        # H is associative, so quaternionic sub-realizations also compose.
        self.assertEqual(self.census.quaternionic_checks, 3)
        self.assertEqual(self.census.quaternionic_non_associative, 0)

    def test_canonical_associator_is_exactly_two_e7(self) -> None:
        witness = canonical_associator_witness()
        expected = octonion(0, 0, 0, 0, 0, 0, 0, 2)
        self.assertEqual(witness.coords, expected.coords)

    def test_explicit_non_associative_triple(self) -> None:
        a = elementary(0, 1, E[1])
        b = elementary(1, 2, E[2])
        c = elementary(2, 0, E[4])
        self.assertFalse(associates(a, b, c))

    def test_artin_two_octonions_always_associate(self) -> None:
        # Any subalgebra generated by TWO octonions is associative (Artin), which
        # is exactly why an h_2(O) realization would still compose. Checked
        # deterministically over a frozen set of pairs and every length-3 word.
        pairs = (
            (octonion(1, 2, 3, 0, 0, 0, 0, 0), octonion(0, 1, 0, 4, 0, 5, 0, 0)),
            (E[1] + E[4], E[2] + E[7]),
            (octonion(1, 1, 0, 0, 1, 0, 0, 1), octonion(0, 2, 3, 0, 0, 0, 4, 0)),
            (E[3], E[6]),
        )
        for p, q in pairs:
            for x, y, z in itertools.product((p, q), repeat=3):
                self.assertEqual(((x * y) * z).coords, (x * (y * z)).coords)
        # And the three-direction obstruction is real for the same alphabet's e4:
        self.assertNotEqual(
            ((E[1] * E[2]) * E[4]).coords, (E[1] * (E[2] * E[4])).coords
        )


if __name__ == "__main__":
    unittest.main()
