"""Octonion campaign: observer-consistency on the last normed division algebra.

This package changes exactly one premise beyond the amplitude campaign: complex
amplitudes over ``Q(i)`` are replaced by octonions over the rationals, the top of
the Cayley-Dickson ladder ``R -> C -> H -> O``. Its gates are the
``tests/test_gate_o*.py`` contracts.
"""

from .octonion import (
    E,
    ONE,
    ZERO,
    UNIT_OCTONIONS,
    Octonion,
    basis,
    cd_mul,
    cd_norm2,
    census_states,
    octonion,
)
from .census import (
    OctonionInvarianceCensus,
    representation_invariance_census,
)
from .frame import (
    FrameConsistencyCensus,
    frame_consistency_census,
    frame_total,
    frames,
    is_orthogonal,
    theorem_witnesses,
)
from .jordan import (
    JordanStateCensus,
    is_jordan_frame,
    is_primitive_idempotent,
    jordan_product,
    jordan_state_census,
    outer,
    trace,
    trace_form,
)
from .composite import (
    CompositeWallCensus,
    associates,
    associator,
    canonical_associator_witness,
    composite_wall_census,
    elementary,
)
from .automorphism import (
    Automorphism,
    AutomorphismCensus,
    apply_jordan,
    apply_octonion,
    automorphism_census,
    automorphism_group,
    is_octonion_automorphism,
)
from .contextuality import (
    ContextualityCensus,
    contexts,
    contextuality_census,
    godsil_zaks_value,
    is_rational_unit_ray,
    odd_position,
    primitive,
    rational_unit_rays,
    ray_to_state,
)
from .born_selection import (
    BornSelectionCensus,
    born_selection_census,
    born_weight,
    contextual_discrepancies,
    frame_consistent_exponents,
    frame_total,
    octonionic_reference_state,
)
from .spin_factor import (
    DimensionThresholdCensus,
    dimension_threshold_census,
    rational_unit_vectors,
)
from .triality import (
    TrialityCensus,
    all_permutations,
    apply_permutation,
    occupied_slots,
    slot_state,
    triality_census,
)
from .spectral import (
    SpectralCensus,
    cayley_hamilton_residual,
    characteristic_coefficients,
    determinant,
    observable,
    spectral_census,
    sylvester_projector,
)

__all__ = [
    "E",
    "ONE",
    "ZERO",
    "UNIT_OCTONIONS",
    "Octonion",
    "basis",
    "cd_mul",
    "cd_norm2",
    "census_states",
    "octonion",
    "OctonionInvarianceCensus",
    "representation_invariance_census",
    "FrameConsistencyCensus",
    "frame_consistency_census",
    "frame_total",
    "frames",
    "is_orthogonal",
    "theorem_witnesses",
    "JordanStateCensus",
    "is_jordan_frame",
    "is_primitive_idempotent",
    "jordan_product",
    "jordan_state_census",
    "outer",
    "trace",
    "trace_form",
    "CompositeWallCensus",
    "associates",
    "associator",
    "canonical_associator_witness",
    "composite_wall_census",
    "elementary",
    "Automorphism",
    "AutomorphismCensus",
    "apply_jordan",
    "apply_octonion",
    "automorphism_census",
    "automorphism_group",
    "is_octonion_automorphism",
    "ContextualityCensus",
    "contexts",
    "contextuality_census",
    "godsil_zaks_value",
    "is_rational_unit_ray",
    "odd_position",
    "primitive",
    "rational_unit_rays",
    "ray_to_state",
    "BornSelectionCensus",
    "born_selection_census",
    "born_weight",
    "contextual_discrepancies",
    "frame_consistent_exponents",
    "frame_total",
    "octonionic_reference_state",
    "DimensionThresholdCensus",
    "dimension_threshold_census",
    "rational_unit_vectors",
    "TrialityCensus",
    "all_permutations",
    "apply_permutation",
    "occupied_slots",
    "slot_state",
    "triality_census",
    "SpectralCensus",
    "cayley_hamilton_residual",
    "characteristic_coefficients",
    "determinant",
    "observable",
    "spectral_census",
    "sylvester_projector",
]
