"""Gate O16 -- octonionic evolution as exact rotations: where the wall lives.

Gate O15 proved a negative at the level of *abstract algebra*: the imaginary
octonions under the commutator are a Malcev algebra, not a Lie algebra, so there
is no octonionic unitary group. This gate makes the same wall *operational* by
representing every evolution step as a concrete exact linear map on the
eight-dimensional state space ``x |-> u x``, and asks the sharp question: exactly
*where* does the non-associativity obstruct dynamics?

The answer, all exact over ``Q``:

1. **Every unit-octonion step is an exact rotation.** For the left-multiplication
   matrix ``L_u`` (``x |-> u x``), ``L_u^T L_u = |u|^2 I``; a unit generator gives
   ``L_u in O(8)`` and an imaginary unit gives a skew generator ``L_a in so(8)``.
   Evolution steps are rigid isometries of the state space.

2. **A single generator integrates to a genuine one-parameter group.** Because the
   subalgebra generated by one element is associative, ``L_u^n = L_{u^n}`` exactly.
   A lone octonionic clock is a bona-fide one-parameter subgroup of ``SO(8)``.

3. **The generators close into a real Lie algebra: ``so(8)``.** The seven imaginary
   ``L_a`` are linearly independent and their repeated commutators span a
   ``28``-dimensional space -- exactly ``so(8) = dim 28``. As *operators*, the
   octonionic flows form an honest Lie algebra.

4. **The wall lives in the map, not the operators.** The assignment ``u |-> L_u`` is
   **not** an algebra homomorphism: ``L_u L_v != L_{uv}``, and the defect applied to
   a state is exactly the associator of Gate O15. The octonionic (Moufang) loop of
   unit octonions has no faithful representation by left multiplication; the whole
   of the non-associativity is this representation defect.

5. **The surviving substitute is Moufang, at operator level.** ``L_u L_v L_u =
   L_{u(vu)}`` holds exactly -- the operator image of the left Moufang identity.

The picture is therefore exact and honest: octonionic dynamics *can* be realised
as rotations in ``SO(8)`` -- there is no obstruction to isometric evolution and the
infinitesimal generators do form the Lie algebra ``so(8)``. The price is that the
finite octonion loop does not act faithfully or associatively: the "algebra of
generators" is Lie (``so(8)``) while the "loop of finite steps" is Malcev/Moufang
(non-associative), and the associator is precisely the gap between them.

Non-claim: this represents single-generator octonionic flow as an exact ``SO(8)``
one-parameter group and *locates* the non-associativity as the failure of
``u |-> L_u`` to be a homomorphism. It does **not** build a two-generator dynamics
or a Hamiltonian, and the ``so(8)`` here is the operator closure of left
multiplications on one octonion copy -- not a claimed physical (gauge or
space-time) symmetry.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import List, Sequence, Tuple

from .color_su3 import Matrix, left_mult_matrix, _matmul, _rref
from .octonion import E, ONE, Octonion, octonion


def _identity() -> Matrix:
    return tuple(
        tuple(Fraction(1) if i == j else Fraction(0) for j in range(8))
        for i in range(8)
    )


def _transpose(a: Matrix) -> Matrix:
    return tuple(tuple(a[j][i] for j in range(8)) for i in range(8))


def _scale(a: Matrix, s: Fraction) -> Matrix:
    return tuple(tuple(s * v for v in row) for row in a)


def _sub(a: Matrix, b: Matrix) -> Matrix:
    return tuple(
        tuple(a[i][j] - b[i][j] for j in range(8)) for i in range(8)
    )


def _commutator(a: Matrix, b: Matrix) -> Matrix:
    return _sub(_matmul(a, b), _matmul(b, a))


def _matrix_power(a: Matrix, n: int) -> Matrix:
    result = _identity()
    for _ in range(n):
        result = _matmul(a, result)
    return result


def octonion_power(u: Octonion, n: int) -> Octonion:
    """The exact power ``u^n`` (well-defined: the subalgebra of one element associates)."""
    result = ONE
    for _ in range(n):
        result = u * result
    return result


def is_orthogonal(u: Octonion) -> bool:
    """Exact check that a *unit* generator acts as an orthogonal (isometric) map."""
    lu = left_mult_matrix(u)
    return _matmul(_transpose(lu), lu) == _identity()


def left_mult_gram(u: Octonion) -> Matrix:
    """``L_u^T L_u`` -- equals ``|u|^2 I`` for every octonion (normed-algebra isometry)."""
    lu = left_mult_matrix(u)
    return _matmul(_transpose(lu), lu)


def single_generator_closes(u: Octonion, upto: int = 7) -> bool:
    """Exact check that ``L_u^n = L_{u^n}`` for ``n = 1..upto`` (one-parameter group)."""
    lu = left_mult_matrix(u)
    return all(
        _matrix_power(lu, n) == left_mult_matrix(octonion_power(u, n))
        for n in range(1, upto + 1)
    )


def homomorphism_defect(u: Octonion, v: Octonion) -> Matrix:
    """``L_u L_v - L_{uv}`` -- the exact failure of ``u |-> L_u`` to be a homomorphism."""
    return _sub(_matmul(left_mult_matrix(u), left_mult_matrix(v)),
                left_mult_matrix(u * v))


def moufang_operator_closes(u: Octonion, v: Octonion) -> bool:
    """Exact check of the operator Moufang law ``L_u L_v L_u = L_{u(vu)}``."""
    lu, lv = left_mult_matrix(u), left_mult_matrix(v)
    return _matmul(_matmul(lu, lv), lu) == left_mult_matrix(u * (v * u))


def _flatten(m: Matrix) -> List[Fraction]:
    return [m[i][j] for i in range(8) for j in range(8)]


def _rank(mats: Sequence[Matrix]) -> int:
    if not mats:
        return 0
    _, pivots = _rref([_flatten(m) for m in mats])
    return len(pivots)


def _independent_basis() -> List[Matrix]:
    """Return an independent basis of the Lie algebra generated by the imaginary
    left multiplications under the commutator, computed by exact rank growth."""
    basis: List[Matrix] = [left_mult_matrix(E[k]) for k in range(1, 8)]
    # Reduce the seed generators to an independent set.
    reduced: List[Matrix] = []
    for m in basis:
        if _rank(reduced + [m]) > len(reduced):
            reduced.append(m)
    changed = True
    while changed:
        changed = False
        current = list(reduced)
        for i in range(len(current)):
            for j in range(i + 1, len(current)):
                c = _commutator(current[i], current[j])
                if _rank(reduced + [c]) > len(reduced):
                    reduced.append(c)
                    changed = True
    return reduced


def lie_closure_dimension() -> int:
    """Dimension of the Lie algebra generated by the imaginary ``L_a`` (``= 28 = so(8)``)."""
    return len(_independent_basis())


def imaginary_generators_independent_dimension() -> int:
    """Dimension of the plain span of the seven imaginary ``L_a`` (``= 7``)."""
    return _rank([left_mult_matrix(E[k]) for k in range(1, 8)])


@dataclass(frozen=True)
class FlowCensus:
    """Exact ledger of octonionic evolution realised as rotations on the state space."""

    steps_are_isometries: bool
    single_generator_group: bool
    imaginary_generator_dimension: int
    lie_closure_dimension: int
    is_so8: bool
    homomorphism_defect_nonzero: bool
    moufang_operator_closes: bool


_U_WITNESS = octonion(0, Fraction(3, 5), Fraction(4, 5), 0, 0, 0, 0, 0)
_V_WITNESS = octonion(0, 0, 0, Fraction(5, 13), Fraction(12, 13), 0, 0, 0)


def flow_census() -> FlowCensus:
    """Assemble the exact operator-level dynamics ledger over ``Q``."""
    closure = lie_closure_dimension()
    return FlowCensus(
        steps_are_isometries=is_orthogonal(_U_WITNESS) and is_orthogonal(_V_WITNESS),
        single_generator_group=single_generator_closes(_U_WITNESS),
        imaginary_generator_dimension=imaginary_generators_independent_dimension(),
        lie_closure_dimension=closure,
        is_so8=(closure == 28),
        homomorphism_defect_nonzero=any(
            v != 0 for row in homomorphism_defect(_U_WITNESS, _V_WITNESS) for v in row
        ),
        moufang_operator_closes=moufang_operator_closes(_U_WITNESS, _V_WITNESS),
    )
