"""Gate O19 -- the U(1) that completes colour to U(3): the phase of the CY slice.

Gate O18 reduced the ``G2`` calibration to an ``SU(3)`` structure on the
Calabi-Yau slice ``u^perp = C^3`` and showed the O10 colour ``su(3)`` is its
structure algebra. But the unitary group of ``C^3`` is ``U(3)``, not ``SU(3)``:
there is one extra generator, the overall *phase*. This gate exhibits it exactly
and characterises it three ways -- and it is precisely the complex structure ``J``
of Gate O18.

Work in ``so(6) = so(u^perp)`` (skew maps of the six-dimensional slice), all exact
over ``Q``.

1. **The phase generator is the complex structure.** ``J = L_u`` restricted to
   ``u^perp`` is skew (``J in so(6)``) with ``J^2 = -I``. Its one-parameter group
   ``exp(theta J)`` is the ``U(1)`` that rotates ``C^3`` by an overall phase.

2. **``u(3)`` is the centraliser of ``J``.** The skew maps commuting with ``J`` --
   the ``J``-complex-linear ones -- form a ``9``-dimensional algebra, exactly
   ``u(3)``, the unitary algebra of the slice.

3. **Colour and phase are mutual centralisers.** Colour ``su(3)`` (dimension ``8``)
   sits inside ``u(3)``, and the centraliser of colour ``su(3)`` *within* ``so(6)``
   is exactly one-dimensional -- the span of ``J``. Hence
   ``u(3) = su(3) (+) u(1)_J``: colour ``SU(3)`` and the phase ``U(1)`` generated by
   ``J`` are each other's commutant and together fill out the full ``U(3)``.

4. **The phase ``U(1)`` is outside ``Aut(O)``.** ``J`` is *not* a derivation of the
   octonions (Gate O17: it does not preserve ``phi``), so ``u(1)_J`` is a genuine
   symmetry beyond ``g2 = Lie(Aut O)`` -- the abelian factor that the choice of a
   preferred direction *adds* to the octonionic automorphisms. It is the centre of
   ``U(3)``, the overall phase of the Calabi-Yau slice (a baryon-number-like
   ``U(1)`` assigning the same charge to all three colours), commuting with colour.

So the geometric reduction of one octonion copy yields not merely colour ``SU(3)``
but ``SU(3) x U(1) = U(3)`` acting on the Calabi-Yau slice, the ``U(1)`` being
forced as the unique commutant of colour and realised by the complex structure.

Non-claim: this exhibits the exact abelian ``u(1)_J`` completing colour ``su(3)``
to ``u(3)`` on the tangent slice, as the commutant of colour and the centre of the
slice's unitary algebra. It does **not** identify this ``U(1)`` with electroweak
hypercharge or electric charge (those need the ``C (x) H (x) O`` structure and the
weak ``su(2)`` of Gate O13, absent here), does not gauge it, and adds no dynamics.
It is the abelian phase of the ``SU(3)`` structure, nothing more.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from typing import List, Tuple

from .color_su3 import Matrix, _rref, is_derivation, left_mult_matrix
from .su3_structure import PERP_INDICES, PREFERRED_UNIT, colour_su3, complex_structure

_DIM = len(PERP_INDICES)  # 6
_SKEW_PAIRS: Tuple[Tuple[int, int], ...] = tuple(
    (i, j) for i in range(_DIM) for j in range(i + 1, _DIM)
)  # 15 = dim so(6)


def _block(matrix: Matrix) -> List[List[Fraction]]:
    """Restrict an 8x8 matrix to the 6x6 block on ``u^perp`` (indices ``e_1..e_6``)."""
    return [[matrix[i][j] for j in PERP_INDICES] for i in PERP_INDICES]


def _commutator(a: List[List[Fraction]], b: List[List[Fraction]]) -> List[List[Fraction]]:
    return [
        [sum(a[i][k] * b[k][j] - b[i][k] * a[k][j] for k in range(_DIM))
         for j in range(_DIM)]
        for i in range(_DIM)
    ]


def _is_skew(m: List[List[Fraction]]) -> bool:
    return all(m[i][j] == -m[j][i] for i in range(_DIM) for j in range(_DIM))


def _matmul6(a: List[List[Fraction]], b: List[List[Fraction]]) -> List[List[Fraction]]:
    return [
        [sum(a[i][k] * b[k][j] for k in range(_DIM)) for j in range(_DIM)]
        for i in range(_DIM)
    ]


def complex_structure_block() -> List[List[Fraction]]:
    """The complex structure ``J`` as a 6x6 skew matrix on ``u^perp``."""
    return _block(complex_structure())


def colour_blocks() -> List[List[List[Fraction]]]:
    """The eight colour ``su(3)`` generators restricted to ``u^perp``."""
    return [_block(d) for d in colour_su3()]


def j_is_skew_square_minus_one() -> bool:
    """Exact check that ``J`` is skew and ``J^2 = -I`` on ``u^perp``."""
    j = complex_structure_block()
    if not _is_skew(j):
        return False
    j2 = _matmul6(j, j)
    return all(
        j2[i][k] == (Fraction(-1) if i == k else Fraction(0))
        for i in range(_DIM) for k in range(_DIM)
    )


def _centraliser_dimension(gens: List[List[List[Fraction]]]) -> int:
    """Dimension of ``{M in so(6) : [M, g] = 0 for all g in gens}``."""
    rows: List[List[Fraction]] = []
    basis = []
    for (p, q) in _SKEW_PAIRS:
        m = [[Fraction(0)] * _DIM for _ in range(_DIM)]
        m[p][q] = Fraction(1)
        m[q][p] = Fraction(-1)
        basis.append(m)
    for g in gens:
        for i in range(_DIM):
            for j in range(_DIM):
                rows.append([_commutator(b, g)[i][j] for b in basis])
    _, pivots = _rref([list(r) for r in rows])
    return len(_SKEW_PAIRS) - len(pivots)


def _skew_vector(m: List[List[Fraction]]) -> List[Fraction]:
    return [m[i][j] for (i, j) in _SKEW_PAIRS]


def _rank(mats: List[List[List[Fraction]]]) -> int:
    _, pivots = _rref([_skew_vector(m) for m in mats])
    return len(pivots)


def centraliser_of_j_dimension() -> int:
    """Dimension of the centraliser of ``J`` in ``so(6)`` (``= 9 = u(3)``)."""
    return _centraliser_dimension([complex_structure_block()])


def commutant_of_colour_dimension() -> int:
    """Dimension of the centraliser of colour ``su(3)`` in ``so(6)`` (``= 1 = u(1)_J``)."""
    return _centraliser_dimension(colour_blocks())


def colour_dimension() -> int:
    """Dimension of the span of the colour blocks on ``u^perp`` (``= 8``)."""
    return _rank(colour_blocks())


def u3_dimension() -> int:
    """Dimension of the span of colour ``su(3)`` together with ``J`` (``= 9 = u(3)``)."""
    return _rank(colour_blocks() + [complex_structure_block()])


def phase_commutes_with_colour() -> bool:
    """Exact check that ``J`` commutes with every colour generator on ``u^perp``."""
    j = complex_structure_block()
    zero = [[Fraction(0)] * _DIM for _ in range(_DIM)]
    return all(_commutator(j, d) == zero for d in colour_blocks())


def phase_is_outside_automorphisms() -> bool:
    """Exact check that ``J = L_u`` is not a derivation of ``O`` (``u(1)_J`` beyond ``g2``)."""
    return not is_derivation(left_mult_matrix(PREFERRED_UNIT))


@dataclass(frozen=True)
class PhaseU1Census:
    """Exact ledger of the abelian ``U(1)`` completing colour ``su(3)`` to ``u(3)``."""

    j_skew_square_minus_one: bool
    centraliser_of_j_dimension: int
    colour_dimension: int
    commutant_of_colour_dimension: int
    u3_dimension: int
    phase_commutes_with_colour: bool
    phase_outside_automorphisms: bool


def phase_u1_census() -> PhaseU1Census:
    """Assemble the exact ``su(3) (+) u(1)_J = u(3)`` ledger over ``Q``."""
    return PhaseU1Census(
        j_skew_square_minus_one=j_is_skew_square_minus_one(),
        centraliser_of_j_dimension=centraliser_of_j_dimension(),
        colour_dimension=colour_dimension(),
        commutant_of_colour_dimension=commutant_of_colour_dimension(),
        u3_dimension=u3_dimension(),
        phase_commutes_with_colour=phase_commutes_with_colour(),
        phase_outside_automorphisms=phase_is_outside_automorphisms(),
    )
