"""
R2 origin — the two-level symmetry descends from the A4 flavour group.
======================================================================

Context (epsilon_free_action.py, residual R2)
---------------------------------------------
epsilon_free_action.py REFRAMED R2: it showed the free kinetic action plus the
topological Berry term is the UNIQUE action invariant under the two-level
U(2) -> SO(3) Bloch-sphere symmetry of the rank-one kernel + complement.  Its one
honest residual was the MICROSCOPIC ORIGIN of that two-level symmetry: why does
the spurion dynamics have a U(2)/SU(2) symmetry at all?

The claim of this module
------------------------
The continuous two-level symmetry is the SU(2) closure of the discrete flavour
group A4 (the tetrahedral group, the standard 3-generation symmetry).  Concretely:

  [A] A4 IS the tetrahedral rotation group in SO(3).  Generated by a 3-cycle of
      the axes (order 3) and a pi-rotation (order 2), it closes to 12 elements
      with class sizes (1, 3, 4, 4) -- the signature of A4.  Its normal Klein
      four-subgroup V4 = {I and the three pi-rotations about x, y, z} is the
      discrete skeleton of a qubit, and the quotient A4/V4 = Z3 is the
      generation grading (three generations, cf. R1: rank-one <-> N_gen = 3).

  [B] LIFT THROUGH THE DOUBLE COVER SU(2) -> SO(3).
        * V4  lifts to the QUATERNION group Q8 = {+-I, +-i sigma_x, +-i sigma_y,
          +-i sigma_z} -- the qubit PAULI group.  So the two-level system's Pauli
          operators ARE the SU(2) preimage of A4's normal Klein subgroup.
        * A4  lifts to the binary tetrahedral group 2T (order 24).

  [C] BURNSIDE / SCHUR: the spinor (2-dim) representation of Q8 (already, before
      using all of 2T) is IRREDUCIBLE, so by Burnside its complex linear span is
      the FULL matrix algebra M2(C) (complex dim 4).  Hence the smallest algebra
      closing the A4-double-cover is M2(C), whose unitaries are U(2) and whose
      anti-Hermitian traceless part is su(2) (dim 3) -- exactly the two-level
      symmetry that epsilon_free_action.py assumed.  The Bloch sphere
      S^2 = SU(2)/U(1) carries A4 as the tetrahedral rotation group.

Net effect on R2
----------------
epsilon_free_action.py: free action forced BY the two-level symmetry.
This module: the two-level symmetry forced BY the A4 flavour group (its Pauli
skeleton Q8 = double cover of V4 < A4, its continuous closure SU(2) by Burnside).
Chained: the free spurion action is forced by the A4 flavour symmetry that also
delivers the three generations (A4/V4 = Z3).  R2's residual shrinks from "why a
two-level symmetry" to the existence of the A4 flavour symmetry itself.

Honest scope
------------
Derived here: A4 = tetrahedral SO(3) group; V4 -> Q8 (Pauli group) and
A4 -> 2T under the double cover; Q8/2T irreducible on C^2 => Burnside span M2(C)
=> continuous closure U(2)/su(2); A4/V4 = Z3.  NOT derived here: that the CHO
spurion sector is acted on by A4 in the first place (A4 as the residual flavour
symmetry of the triality-broken vacuum is the standing assumption that this
module REDUCES the two-level symmetry to).

numpy only.  No scipy.  Self-contained (no repo imports).

Run:
    PYTHONDONTWRITEBYTECODE=1 python3 compute/epsilon_a4_two_level.py
"""

from __future__ import annotations

import numpy as np


# Pauli matrices.
SIGMA_X = np.array([[0.0, 1.0], [1.0, 0.0]], dtype=complex)
SIGMA_Y = np.array([[0.0, -1.0j], [1.0j, 0.0]], dtype=complex)
SIGMA_Z = np.array([[1.0, 0.0], [0.0, -1.0]], dtype=complex)


# --------------------------------------------------------------------------
# [A] A4 as the tetrahedral rotation group in SO(3)
# --------------------------------------------------------------------------


def _key(M: np.ndarray) -> tuple:
    """Hashable rounded key for a real matrix, for set membership."""
    return tuple(np.round(M, 6).ravel())


def close_group(generators: list, dim: int, tol: float = 1e-6) -> list:
    """Close a set of matrices under multiplication (finite group)."""
    elements = {_key(np.eye(dim)): np.eye(dim)}
    frontier = [np.eye(dim)] + list(generators)
    for g in generators:
        elements[_key(g)] = g
    changed = True
    while changed:
        changed = False
        current = list(elements.values())
        for a in current:
            for b in current:
                p = a @ b
                k = _key(p)
                if k not in elements:
                    elements[k] = p
                    changed = True
        if len(elements) > 10 * 60:  # safety against runaway (|A4|=12, |S4|=24)
            break
    return list(elements.values())


def tetrahedral_group() -> list:
    """A4 < SO(3): generated by a 3-cycle of axes and a pi-rotation about z."""
    # 3-cycle x -> y -> z -> x (rotation by 120 deg about (1,1,1)), det +1.
    a = np.array([[0.0, 0.0, 1.0],
                  [1.0, 0.0, 0.0],
                  [0.0, 1.0, 0.0]])
    # pi-rotation about z, det +1.
    b = np.array([[-1.0, 0.0, 0.0],
                  [0.0, -1.0, 0.0],
                  [0.0, 0.0, 1.0]])
    return close_group([a, b], dim=3)


def rotation_angle(R: np.ndarray) -> float:
    """Rotation angle of an SO(3) matrix from its trace."""
    c = (np.trace(R) - 1.0) / 2.0
    c = max(-1.0, min(1.0, c))
    return float(np.arccos(c))


def conjugacy_class_sizes(group: list, tol: float = 1e-6) -> list:
    """Sizes of conjugacy classes (used to fingerprint A4 as 1+3+4+4)."""
    n = len(group)
    seen = [False] * n
    sizes = []
    for i in range(n):
        if seen[i]:
            continue
        cls = set()
        for g in group:
            ginv = g.T  # orthogonal
            conj = g @ group[i] @ ginv
            for j in range(n):
                if np.allclose(conj, group[j], atol=tol):
                    cls.add(j)
                    break
        for j in cls:
            seen[j] = True
        sizes.append(len(cls))
    return sorted(sizes)


def klein_four_subgroup(group: list) -> list:
    """V4 = identity + the three pi-rotations (180 deg), the Pauli skeleton."""
    out = []
    for g in group:
        ang = rotation_angle(g)
        if abs(ang) < 1e-6 or abs(ang - np.pi) < 1e-6:
            out.append(g)
    return out


# --------------------------------------------------------------------------
# [B] Double cover SU(2) -> SO(3): lift V4 -> Q8, A4 -> 2T
# --------------------------------------------------------------------------


def su2_from_so3(R: np.ndarray) -> np.ndarray:
    """One SU(2) preimage of R (the other is its negative)."""
    angle = rotation_angle(R)
    if abs(angle) < 1e-9:
        return np.eye(2, dtype=complex)
    if abs(angle - np.pi) < 1e-9:
        # axis from the symmetric part: R + I = 2 n n^T.
        M = (R + np.eye(3)) / 2.0
        idx = int(np.argmax(np.diag(M)))
        axis = M[:, idx] / np.sqrt(M[idx, idx])
    else:
        axis = np.array([R[2, 1] - R[1, 2],
                         R[0, 2] - R[2, 0],
                         R[1, 0] - R[0, 1]])
        axis = axis / (2.0 * np.sin(angle))
    n = axis / np.linalg.norm(axis)
    gen = n[0] * SIGMA_X + n[1] * SIGMA_Y + n[2] * SIGMA_Z
    return np.cos(angle / 2.0) * np.eye(2) - 1.0j * np.sin(angle / 2.0) * gen


def _ckey(M: np.ndarray) -> tuple:
    return tuple(np.round(M, 6).ravel())


def double_cover(group: list) -> list:
    """The SU(2) preimage {+-U} of an SO(3) subgroup (order doubles)."""
    elements = {}
    for R in group:
        U = su2_from_so3(R)
        for V in (U, -U):
            elements[_ckey(V)] = V
    return list(elements.values())


def is_quaternion_group(elems: list) -> dict:
    """Check the 8 lifted V4 elements ARE Q8 = {+-I, +-i sigma}."""
    targets = [np.eye(2, dtype=complex)]
    for s in (SIGMA_X, SIGMA_Y, SIGMA_Z):
        targets.append(1.0j * s)
    full = []
    for T in targets:
        full.append(T)
        full.append(-T)
    matched = 0
    for T in full:
        if any(np.allclose(T, E, atol=1e-6) for E in elems):
            matched += 1
    return {"order": len(elems), "matched_pauli_group": matched, "is_Q8": matched == 8}


# --------------------------------------------------------------------------
# [C] Burnside / Schur: irreducible 2-dim rep spans M2(C) -> closure U(2)
# --------------------------------------------------------------------------


def burnside_span_dimension(elems: list) -> int:
    """Complex dim of the linear span of a set of 2x2 matrices (M2(C) = 4)."""
    vs = np.array([E.ravel() for E in elems])  # rows = vec(E), complex
    # Rank over C via SVD of the complex matrix.
    s = np.linalg.svd(vs, compute_uv=False)
    return int(np.sum(s > 1e-9))


def commutant_dimension(elems: list) -> int:
    """Complex dim of {X : X E = E X for all E} -- 1 iff irreducible (Schur)."""
    rows = []
    for E in elems:
        # vec(E X - X E) = (I (x) E - E^T (x) I) vec(X) = 0.
        rows.append(np.kron(np.eye(2), E) - np.kron(E.T, np.eye(2)))
    A = np.vstack(rows)
    s = np.linalg.svd(A, compute_uv=False)
    rank = int(np.sum(s > 1e-9))
    return 4 - rank


def su2_lie_algebra_dimension(elems: list) -> int:
    """Real dim of the span of the traceless anti-Hermitian parts (su(2) = 3)."""
    gens = []
    for E in elems:
        A = E - E.conj().T              # anti-Hermitian part
        A = A - np.trace(A) / 2.0 * np.eye(2)  # traceless
        if np.linalg.norm(A) > 1e-9:
            gens.append(A.ravel())
    if not gens:
        return 0
    # Real dimension: stack real and imaginary parts.
    M = np.array(gens)
    real_rows = np.vstack([M.real, M.imag])
    s = np.linalg.svd(real_rows, compute_uv=False)
    return int(np.sum(s > 1e-9))


# --------------------------------------------------------------------------
# A4 / V4 = Z3 (the generation grading)
# --------------------------------------------------------------------------


def quotient_is_z3(group: list, v4: list, tol: float = 1e-6) -> dict:
    """A4/V4 has order 3 and is cyclic (the three generations)."""

    def in_v4(M):
        return any(np.allclose(M, h, atol=tol) for h in v4)

    # Cosets g V4.
    cosets = []
    for g in group:
        rep_set = [g @ h for h in v4]
        # Identify by a canonical key of the sorted coset.
        is_new = True
        for c in cosets:
            if any(np.allclose(g, x, atol=tol) for x in c):
                is_new = False
                break
        if is_new:
            cosets.append(rep_set)
    order = len(cosets)
    # Normality: g V4 g^-1 = V4 for all g.
    normal = all(in_v4(g @ h @ g.T) for g in group for h in v4)
    return {"quotient_order": order, "normal": normal, "is_Z3": order == 3 and normal}


# --------------------------------------------------------------------------
# Report
# --------------------------------------------------------------------------


def main() -> None:
    print("=" * 78)
    print("  R2 origin — the two-level symmetry descends from the A4 flavour group")
    print("=" * 78)
    print()

    a4 = tetrahedral_group()
    classes = conjugacy_class_sizes(a4)
    v4 = klein_four_subgroup(a4)
    print("-" * 78)
    print("  [A] A4 = tetrahedral rotation group in SO(3)")
    print("-" * 78)
    print(f"      |A4|                 = {len(a4)}   (expect 12)")
    print(f"      conjugacy classes    = {classes}   (expect [1, 3, 4, 4])")
    print(f"      |V4| (pi-rotations)  = {len(v4)}    (Klein four, the qubit skeleton)")
    a_ok = (len(a4) == 12 and classes == [1, 3, 4, 4] and len(v4) == 4)
    print(f"      [{'PASS' if a_ok else 'FAIL'}] A4 with normal Klein subgroup V4")
    print()

    q8 = double_cover(v4)
    tt = double_cover(a4)
    q8_check = is_quaternion_group(q8)
    print("-" * 78)
    print("  [B] Double cover SU(2) -> SO(3): V4 -> Q8 (Pauli group), A4 -> 2T")
    print("-" * 78)
    print(f"      |Q8| = lift(V4)      = {q8_check['order']}    (expect 8 = quaternion group)")
    print(f"      Pauli-group match    = {q8_check['matched_pauli_group']}/8  "
          "({+-I, +-i sigma_x, +-i sigma_y, +-i sigma_z})")
    print(f"      |2T| = lift(A4)      = {len(tt)}   (expect 24 = binary tetrahedral)")
    b_ok = q8_check["is_Q8"] and len(tt) == 24
    print(f"      [{'PASS' if b_ok else 'FAIL'}] the qubit Pauli group Q8 = double cover "
          "of V4 < A4")
    print()

    span = burnside_span_dimension(q8)
    comm = commutant_dimension(q8)
    su2 = su2_lie_algebra_dimension(q8)
    print("-" * 78)
    print("  [C] Burnside/Schur: irreducible 2-dim rep -> closure U(2)/su(2)")
    print("-" * 78)
    print(f"      commutant dim        = {comm}   (1 = irreducible, Schur)")
    print(f"      span dim (Burnside)  = {span}   (4 = full M2(C))")
    print(f"      su(2) generated dim  = {su2}   (3 = {{i sigma_x, i sigma_y, i sigma_z}})")
    c_ok = (comm == 1 and span == 4 and su2 == 3)
    print(f"      [{'PASS' if c_ok else 'FAIL'}] continuous closure of the A4 cover is "
          "U(2) (su(2) dim 3)")
    print()

    z3 = quotient_is_z3(a4, v4)
    print("-" * 78)
    print("  A4 / V4 = Z3  (the generation grading)")
    print("-" * 78)
    print(f"      quotient order       = {z3['quotient_order']}   (expect 3)")
    print(f"      V4 normal in A4      = {z3['normal']}")
    z_ok = z3["is_Z3"]
    print(f"      [{'PASS' if z_ok else 'FAIL'}] A4/V4 = Z3 -> three generations "
          "(cf. R1 N_gen=3)")
    print()

    print("=" * 78)
    print("  VERDICT")
    print("=" * 78)
    if a_ok and b_ok and c_ok and z_ok:
        print("  R2 origin status: DERIVED. The two-level (qubit) symmetry that")
        print("  epsilon_free_action.py used to force the free spurion action is the")
        print("  SU(2) closure of the A4 flavour group: A4's normal Klein subgroup V4")
        print("  (the three pi-rotations) lifts under the double cover SU(2) -> SO(3) to")
        print("  the qubit Pauli group Q8 = {+-I, +-i sigma}, whose irreducible 2-dim")
        print("  rep spans M2(C) (Burnside) so its continuous closure is U(2)/su(2) --")
        print("  exactly the two-level symmetry. The Bloch sphere S^2 = SU(2)/U(1)")
        print("  carries A4 as tetrahedral rotations, and A4/V4 = Z3 is the three-")
        print("  generation grading (cf. R1). The free action is thus forced by the")
        print("  same A4 flavour symmetry that delivers N_gen = 3.")
        print()
        print("  Honest residual: that the triality-broken CHO vacuum is acted on by A4")
        print("  in the first place is the standing flavour-symmetry assumption that")
        print("  this module REDUCES the two-level symmetry to -- not an independent")
        print("  new input, but the origin of A4 itself is the remaining open step.")
    else:
        print("  R2 origin status: OPEN — a group, lift, Burnside, or quotient check")
        print("  failed above.")
    print()


if __name__ == "__main__":
    main()
