"""
F4-BREAKING BINARY PROJECTOR HISTORY GATE -- where do binary histories come from?
================================================================================

The maximum-caliber gate derived the independent Bernoulli ensemble once binary
projective-transition histories and a mean transition density were granted. This
gate climbs one rung underneath that granted binary alphabet.

In the OP^2/Jordan projector geometry, a primitive transition question is a
rank-one idempotent Q. The event algebra generated by Q has exactly the yes/no
effects

    yes = Q,        no = I - Q,

with Q o Q = Q, (I-Q) o (I-Q) = I-Q, Q o (I-Q) = 0, and yes+no = I. For a
rank-one source state P, the Born probabilities are

    p_yes = Tr(P o Q),        p_no = Tr(P o (I-Q)) = 1 - p_yes.

At the selected projective transition, p_yes = pi/432. Repeated observations of
this primitive yes/no event have the binary history alphabet {0,1}^N and binomial
counting multiplicities C(N,k), which is the path space used by MaxCal and the
large-deviation source gate.

What this proves
----------------
The binary history alphabet is not an arbitrary statistical wrapper once the
physical datum is a primitive projective transition question in OP^2. The two
outcomes are the Boolean subalgebra generated by a primitive idempotent, and the
binomial history counting follows from repeated yes/no readout.

What this still does not prove
------------------------------
This does not derive why CHO/F4 dynamics selects this primitive transition as the
physical source question, why its mean is the WZ/Born density pi/432, or why the
MaxCal/path-entropy principle is the action. The live bridge is now the origin of
the primitive source question and mean constraint in the F4-breaking dynamics.

No Bayes credit moves.

Run:
    PYTHONDONTWRITEBYTECODE=1 python3 compute/f4_breaking_binary_projector_history_gate.py
"""

from __future__ import annotations

from dataclasses import dataclass
import math

import numpy as np

from epsilon_action_selection import (
    cubic_norm,
    jordan_product,
    random_automorphism,
    trace_form,
    _f4_basis,
)
from epsilon_orbit_selection import primitive_idempotents
from f4_breaking_born_geometry_gate import octonionic_support, transition_projectors
from f4_breaking_maxcal_ensemble_gate import (
    maxcal_lagrange_multiplier,
    maxcal_probability_from_multiplier,
)
from f4_breaking_seed_op2 import EPS0, EPS0_SQ
from f4_breaking_source_stationarity_gate import beta_for_source, model_probability


TOL = 1e-12
F4_TOL = 1e-9
MATCH_TOL = 1e-14
MISS_TOL = 1e-3
MIN_OCTONIONIC = 0.05


@dataclass(frozen=True)
class BinaryProjectorRow:
    label: str
    amplitude: float
    yes_probability: float
    no_probability: float
    probability_sum_error: float
    yes_idempotent_error: float
    no_idempotent_error: float
    orthogonality_error: float
    target_error: float
    binary_projector_event: bool
    matches_target: bool
    interpretation: str


@dataclass(frozen=True)
class F4BinaryTransportWitness:
    base_yes_probability: float
    max_yes_probability_error: float
    max_probability_sum_error: float
    max_idempotent_error: float
    max_orthogonality_error: float
    max_rank_error: float
    min_octonionic_support: float


@dataclass(frozen=True)
class BinaryHistoryCountingRow:
    total_trials: int
    history_count: int
    binomial_count_sum: int
    count_sum_error: int
    probability_sum: float
    probability_sum_error: float
    mean_success_density: float
    mean_error: float
    variance_density: float
    binomial_variance_density: float
    variance_error: float


@dataclass(frozen=True)
class BinaryProjectorSelection:
    source_density: float
    no_density: float
    maxcal_lagrange_multiplier: float
    maxcal_probability: float
    stationary_beta: float
    stationary_amplitude: float
    stationary_probability: float
    binary_history_space_derived: bool
    binomial_counting_derived: bool
    primitive_source_question_derived_from_cho: bool
    cho_mean_constraint_derived: bool
    maxcal_action_derived_from_cho: bool


def identity_idempotent() -> np.ndarray:
    frame = primitive_idempotents()
    return frame[0] + frame[1] + frame[2]


def projector_complement(projector: np.ndarray) -> np.ndarray:
    return identity_idempotent() - projector


def binary_projector_row(label: str, amplitude: float, interpretation: str) -> BinaryProjectorRow:
    if not 0.0 < amplitude < 1.0:
        raise ValueError("amplitude must lie in (0, 1)")
    _psi, _phi, source_projector, event_projector = transition_projectors(amplitude)
    complement = projector_complement(event_projector)
    yes_probability = trace_form(source_projector, event_projector)
    no_probability = trace_form(source_projector, complement)
    yes_idempotent_error = float(np.linalg.norm(jordan_product(event_projector, event_projector) - event_projector))
    no_idempotent_error = float(np.linalg.norm(jordan_product(complement, complement) - complement))
    orthogonality_error = float(np.linalg.norm(jordan_product(event_projector, complement)))
    target_error = abs(yes_probability - EPS0_SQ)
    binary_projector_event = (
        yes_idempotent_error < TOL
        and no_idempotent_error < TOL
        and orthogonality_error < TOL
        and abs(yes_probability + no_probability - 1.0) < TOL
    )
    return BinaryProjectorRow(
        label=label,
        amplitude=float(amplitude),
        yes_probability=float(yes_probability),
        no_probability=float(no_probability),
        probability_sum_error=abs(yes_probability + no_probability - 1.0),
        yes_idempotent_error=yes_idempotent_error,
        no_idempotent_error=no_idempotent_error,
        orthogonality_error=orthogonality_error,
        target_error=float(target_error),
        binary_projector_event=bool(binary_projector_event),
        matches_target=target_error < MATCH_TOL,
        interpretation=interpretation,
    )


def scaled_effect_row(scale: float = 1.0 / 432.0) -> BinaryProjectorRow:
    _psi, _phi, source_projector, _event_projector = transition_projectors(EPS0)
    effect = scale * identity_idempotent()
    complement = identity_idempotent() - effect
    yes_probability = trace_form(source_projector, effect)
    no_probability = trace_form(source_projector, complement)
    yes_idempotent_error = float(np.linalg.norm(jordan_product(effect, effect) - effect))
    no_idempotent_error = float(np.linalg.norm(jordan_product(complement, complement) - complement))
    orthogonality_error = float(np.linalg.norm(jordan_product(effect, complement)))
    target_error = abs(yes_probability - EPS0_SQ)
    return BinaryProjectorRow(
        label="state-count scaled effect",
        amplitude=float(math.sqrt(scale)),
        yes_probability=float(yes_probability),
        no_probability=float(no_probability),
        probability_sum_error=abs(yes_probability + no_probability - 1.0),
        yes_idempotent_error=yes_idempotent_error,
        no_idempotent_error=no_idempotent_error,
        orthogonality_error=orthogonality_error,
        target_error=float(target_error),
        binary_projector_event=False,
        matches_target=False,
        interpretation="wrong: normalized effect is not an idempotent projective yes/no question and omits Berry pi",
    )


def binary_projector_rows() -> tuple[BinaryProjectorRow, ...]:
    return (
        binary_projector_row(
            "selected primitive event",
            EPS0,
            "correct: primitive projector question Q with Tr(P o Q)=pi/432",
        ),
        binary_projector_row(
            "level-two primitive event",
            math.sqrt(2.0 * EPS0_SQ),
            "wrong source: still a binary projector event, but its WZ level is k=2",
        ),
        binary_projector_row(
            "state-count primitive event",
            math.sqrt(1.0 / 432.0),
            "wrong source: binary projector event with the Schur count but without Berry pi",
        ),
        scaled_effect_row(),
    )


def f4_binary_transport_witness(n_auto: int = 8, seed: int = 20260610) -> F4BinaryTransportWitness:
    _psi, _phi, source_projector, event_projector = transition_projectors(EPS0)
    identity = identity_idempotent()
    base_yes_probability = trace_form(source_projector, event_projector)
    rng = np.random.default_rng(seed)
    f4 = _f4_basis()
    max_yes_probability_error = 0.0
    max_probability_sum_error = 0.0
    max_idempotent_error = 0.0
    max_orthogonality_error = 0.0
    max_rank_error = 0.0
    min_octonionic = math.inf
    for _ in range(n_auto):
        automorphism = random_automorphism(rng, f4, 0.9)
        transported_source = automorphism @ source_projector
        transported_event = automorphism @ event_projector
        transported_complement = identity - transported_event
        yes_probability = trace_form(transported_source, transported_event)
        no_probability = trace_form(transported_source, transported_complement)
        max_yes_probability_error = max(max_yes_probability_error, abs(yes_probability - base_yes_probability))
        max_probability_sum_error = max(max_probability_sum_error, abs(yes_probability + no_probability - 1.0))
        for effect in (transported_event, transported_complement):
            max_idempotent_error = max(
                max_idempotent_error,
                float(np.linalg.norm(jordan_product(effect, effect) - effect)),
            )
        max_orthogonality_error = max(
            max_orthogonality_error,
            float(np.linalg.norm(jordan_product(transported_event, transported_complement))),
        )
        for projector in (transported_source, transported_event):
            max_rank_error = max(max_rank_error, abs(cubic_norm(projector)))
        min_octonionic = min(
            min_octonionic,
            max(octonionic_support(transported_source), octonionic_support(transported_event)),
        )
    return F4BinaryTransportWitness(
        base_yes_probability=float(base_yes_probability),
        max_yes_probability_error=float(max_yes_probability_error),
        max_probability_sum_error=float(max_probability_sum_error),
        max_idempotent_error=float(max_idempotent_error),
        max_orthogonality_error=float(max_orthogonality_error),
        max_rank_error=float(max_rank_error),
        min_octonionic_support=float(min_octonionic),
    )


def _binomial_coefficient(total_trials: int, successes: int) -> int:
    return math.factorial(total_trials) // (math.factorial(successes) * math.factorial(total_trials - successes))


def binary_history_counting_rows() -> tuple[BinaryHistoryCountingRow, ...]:
    probability = EPS0_SQ
    rows = []
    for total_trials in (4, 8, 12):
        history_count = 2 ** total_trials
        binomial_count_sum = sum(_binomial_coefficient(total_trials, successes) for successes in range(total_trials + 1))
        probability_sum = 0.0
        mean_successes = 0.0
        mean_successes_squared = 0.0
        for successes in range(total_trials + 1):
            multiplicity = _binomial_coefficient(total_trials, successes)
            probability_mass = multiplicity * (probability ** successes) * ((1.0 - probability) ** (total_trials - successes))
            probability_sum += probability_mass
            mean_successes += successes * probability_mass
            mean_successes_squared += (successes * successes) * probability_mass
        mean_density = mean_successes / total_trials
        variance_successes = mean_successes_squared - mean_successes * mean_successes
        variance_density = variance_successes / (total_trials * total_trials)
        binomial_variance_density = probability * (1.0 - probability) / total_trials
        rows.append(
            BinaryHistoryCountingRow(
                total_trials=int(total_trials),
                history_count=int(history_count),
                binomial_count_sum=int(binomial_count_sum),
                count_sum_error=int(abs(binomial_count_sum - history_count)),
                probability_sum=float(probability_sum),
                probability_sum_error=abs(probability_sum - 1.0),
                mean_success_density=float(mean_density),
                mean_error=abs(mean_density - probability),
                variance_density=float(variance_density),
                binomial_variance_density=float(binomial_variance_density),
                variance_error=abs(variance_density - binomial_variance_density),
            )
        )
    return tuple(rows)


def binary_projector_selection() -> BinaryProjectorSelection:
    density = EPS0_SQ
    lagrange_multiplier = maxcal_lagrange_multiplier(density)
    beta = beta_for_source(density, power=2)
    return BinaryProjectorSelection(
        source_density=float(density),
        no_density=float(1.0 - density),
        maxcal_lagrange_multiplier=float(lagrange_multiplier),
        maxcal_probability=float(maxcal_probability_from_multiplier(lagrange_multiplier)),
        stationary_beta=float(beta),
        stationary_amplitude=float(math.exp(-beta)),
        stationary_probability=float(model_probability(beta, power=2)),
        binary_history_space_derived=True,
        binomial_counting_derived=True,
        primitive_source_question_derived_from_cho=False,
        cho_mean_constraint_derived=False,
        maxcal_action_derived_from_cho=False,
    )


def main() -> bool:
    rows = binary_projector_rows()
    transport = f4_binary_transport_witness()
    history_rows = binary_history_counting_rows()
    selection = binary_projector_selection()
    target_beta = -math.log(EPS0)

    print("=" * 78)
    print("F4-BREAKING BINARY PROJECTOR HISTORY GATE")
    print("Does a primitive OP2 projector force the binary history alphabet?")
    print("=" * 78)

    print("\n[A] Projective yes/no event algebra")
    for row in rows:
        print(
            f"  {row.label:<28} amp={row.amplitude:.12f} yes={row.yes_probability:.12f} "
            f"no={row.no_probability:.12f} sum_err={row.probability_sum_error:.2e} "
            f"idem=({row.yes_idempotent_error:.1e},{row.no_idempotent_error:.1e}) "
            f"orth={row.orthogonality_error:.1e} |yes-target|={row.target_error:.3e} "
            f"binary={row.binary_projector_event} match={row.matches_target}"
        )
        print(f"      {row.interpretation}")

    print("\n[B] F4 transport of the binary event")
    print(f"  base yes probability                   : {transport.base_yes_probability:.15f}")
    print(f"  max transported yes-probability error  : {transport.max_yes_probability_error:.2e}")
    print(f"  max transported probability-sum error  : {transport.max_probability_sum_error:.2e}")
    print(f"  max transported idempotent error       : {transport.max_idempotent_error:.2e}")
    print(f"  max transported orthogonality error    : {transport.max_orthogonality_error:.2e}")
    print(f"  max transported rank-one error         : {transport.max_rank_error:.2e}")
    print(f"  min genuine octonionic support         : {transport.min_octonionic_support:.3f}")

    print("\n[C] Repeated yes/no readout gives binomial history counting")
    for row in history_rows:
        print(
            f"  N={row.total_trials:<2} histories={row.history_count:<5} "
            f"sum_C(N,k)={row.binomial_count_sum:<5} count_err={row.count_sum_error} "
            f"prob_sum={row.probability_sum:.12f} mean={row.mean_success_density:.12f} "
            f"var/N^2={row.variance_density:.6e} var_err={row.variance_error:.2e}"
        )

    print("\n[D] Reconnect binary projector histories to MaxCal and beta")
    print(f"  source density d                         : {selection.source_density:.15f}")
    print(f"  no-event density 1-d                     : {selection.no_density:.15f}")
    print(f"  MaxCal lambda                            : {selection.maxcal_lagrange_multiplier:.12f}")
    print(f"  MaxCal q(lambda)                         : {selection.maxcal_probability:.15f}")
    print(f"  stationary beta                          : {selection.stationary_beta:.12f}")
    print(f"  target beta=-log(eps0)                   : {target_beta:.12f}")
    print(f"  exp(-beta)                               : {selection.stationary_amplitude:.15f}")
    print(f"  exp(-2 beta)                             : {selection.stationary_probability:.15f}")

    print("\n[V] Verdict")
    print("  binary histories from primitive projector : YES, conditional")
    print("  binomial counting alphabet derived        : YES")
    print("  primitive source question from CHO action : NO")
    print("  CHO mean/source constraint derived        : NO")
    print("  MaxCal/action principle derived           : NO")
    print("  Bayes/scoreboard credit moved             : NO")
    print("=" * 78)

    matching = [row for row in rows if row.matches_target]
    misses = [row for row in rows if not row.matches_target]
    assert len(matching) == 1
    assert matching[0].label == "selected primitive event"
    assert all(row.binary_projector_event for row in rows[:3])
    assert not rows[-1].binary_projector_event
    assert all(row.target_error > MISS_TOL for row in misses)
    assert transport.max_yes_probability_error < F4_TOL
    assert transport.max_probability_sum_error < F4_TOL
    assert transport.max_idempotent_error < F4_TOL
    assert transport.max_orthogonality_error < F4_TOL
    assert transport.max_rank_error < F4_TOL
    assert transport.min_octonionic_support > MIN_OCTONIONIC
    assert all(row.count_sum_error == 0 for row in history_rows)
    assert all(row.probability_sum_error < TOL for row in history_rows)
    assert all(row.mean_error < TOL for row in history_rows)
    assert all(row.variance_error < TOL for row in history_rows)
    assert abs(selection.source_density - EPS0_SQ) < MATCH_TOL
    assert abs(selection.no_density + selection.source_density - 1.0) < MATCH_TOL
    assert abs(selection.maxcal_probability - EPS0_SQ) < MATCH_TOL
    assert abs(selection.stationary_beta - target_beta) < MATCH_TOL
    assert abs(selection.stationary_amplitude - EPS0) < MATCH_TOL
    assert abs(selection.stationary_probability - EPS0_SQ) < MATCH_TOL
    assert selection.binary_history_space_derived
    assert selection.binomial_counting_derived
    assert not selection.primitive_source_question_derived_from_cho
    assert not selection.cho_mean_constraint_derived
    assert not selection.maxcal_action_derived_from_cho
    return True


if __name__ == "__main__":
    raise SystemExit(0 if main() else 1)