"""
Lever B — KO-dimension of the octonionic internal space (the chirality test).
=============================================================================

Why this is THE decisive cheap test
-----------------------------------
The triality route to generations failed (three_generations_nogo_audit.py)
because the two spinor reps 8s, 8c form an opposite-chirality MIRROR PAIR: a
left-handed generation comes with a right-handed partner, i.e. fermion doubling.
This is exactly the disease that Connes' noncommutative-geometry Standard Model
CURES with a real structure J whose KO-dimension is 6 (mod 8). At KO-dimension 6
the conditions

    J^2 = +1   (epsilon  = +1)
    J gamma = - gamma J   (epsilon'' = -1)

let the physical fermions live in the +1 eigenspace of the grading operator
without their mirror partners -- chirality WITHOUT doubling.

So there is a single integer that decides whether the CHO internal space can be
chiral at all: its KO-dimension mod 8. If it is 6, the framework is chiral-
capable (same value Connes needs). If it is anything else, the mirror problem is
structural and no amount of model-building removes it.

What this module actually computes (no hand-set answer)
-------------------------------------------------------
It builds everything from the octonion multiplication table and lets the signs
come out of explicit matrices:

  1. Left multiplications L_{e_i} (i=1..7) as 8x8 REAL matrices.
  2. VERIFY they satisfy the Clifford relations {L_i, L_j} = -2 delta_ij,
     i.e. they generate Cl(0,7); and that the complexified algebra they
     generate is all of M_8(C) = C(8) (the Furey / Dubois-Violette statement
     that C (x) O ~ Cl(6) acts irreducibly on C^8).
  3. Build the real structure  J = (complex conjugation) o (octonion
     conjugation)  and compute  epsilon = sign(J^2).
  4. Build the chirality grading  gamma = i * L_1 L_2 ... L_6  (volume element
     of the 6 generators), verify gamma^2 = +1 and that it splits C^8 into two
     Weyl halves 4 + 4, then compute  epsilon'' from  J gamma = epsilon'' gamma J.
  5. Map (epsilon, epsilon'') -> KO-dimension via the Connes-Barrett sign table
     and PRINT the result, whatever it is.

If the computed pair is (epsilon, epsilon'') = (+1, -1) the internal space sits
at KO-dimension 6 and is chiral-capable; this is the go/no-go for the whole
chirality story.

No scipy. Uses octonion_toolkit.OCT_MULT and numpy.

Run:
    PYTHONDONTWRITEBYTECODE=1 python3 compute/ko_dimension_chirality.py
"""

import numpy as np

from octonion_toolkit import OCT_MULT


# --------------------------------------------------------------------------
# Left-multiplication matrices L_{e_i} on the octonions (8x8 real)
# --------------------------------------------------------------------------
def left_mult_matrix(i):
    """8x8 real matrix of x -> e_i * x in the basis e_0..e_7.

    (L_{e_i})_{k,j} = coefficient of e_k in e_i * e_j = OCT_MULT[i, j, k].
    """
    L = np.zeros((8, 8))
    for j in range(8):
        for k in range(8):
            L[k, j] = OCT_MULT[i, j, k]
    return L


def build_generators():
    """Return the 7 imaginary left-multiplications as 8x8 real matrices."""
    return [left_mult_matrix(i) for i in range(1, 8)]


# --------------------------------------------------------------------------
# Checks
# --------------------------------------------------------------------------
def check_clifford(gens, tol=1e-12):
    """Verify {L_i, L_j} = -2 delta_ij  (Cl(0,7) generating relations)."""
    n = len(gens)
    I = np.eye(8)
    ok = True
    max_err = 0.0
    for a in range(n):
        for b in range(n):
            anti = gens[a] @ gens[b] + gens[b] @ gens[a]
            target = -2.0 * (1.0 if a == b else 0.0) * I
            err = np.max(np.abs(anti - target))
            max_err = max(max_err, err)
            if err > tol:
                ok = False
    return ok, max_err


def check_irreducible_complex(gens, tol=1e-9):
    """The complexified algebra generated by the L_i should be all of C(8).

    Grow the associative algebra generated by {I, L_1..L_6} under matrix
    multiplication, tracking an orthonormal basis of the flattened matrices,
    and check the saturated complex dimension is 64 = dim_C M_8(C).
    Six generators suffice (Cl(0,6) ~ R(8) -> C(8) on complexification); the
    seventh L_7 is the volume element and adds nothing to the algebra.
    """
    G = [g.astype(np.complex128) for g in gens[:6]]
    basis_vecs = []      # orthonormal flattened basis of the algebra
    accepted = []        # the matrices kept

    def try_add(M):
        v = M.reshape(-1).astype(np.complex128)
        for b in basis_vecs:
            v = v - np.vdot(b, v) * b
        if np.linalg.norm(v) > tol:
            basis_vecs.append(v / np.linalg.norm(v))
            accepted.append(M)
            return True
        return False

    try_add(np.eye(8, dtype=np.complex128))
    for g in G:
        try_add(g)

    changed = True
    while changed and len(basis_vecs) < 64:
        changed = False
        snapshot = list(accepted)
        for g in G:
            for M in snapshot:
                if try_add(g @ M):
                    changed = True
    dim = len(basis_vecs)
    return dim, dim == 64


# --------------------------------------------------------------------------
# Real structure J and grading gamma; epsilon and epsilon''
# --------------------------------------------------------------------------
# The correct real structure for the complexification C (x) O is plain complex
# conjugation K: its fixed points are exactly the REAL octonions O sitting
# inside C (x) O. (Octonion conjugation is a different map -- an algebra
# anti-automorphism that turns left- into right-multiplication -- and is NOT
# the complexification's real structure.) Since the generators L_{e_i} are real
# matrices, J = K is also the canonical real structure of the real Clifford
# algebra they generate. We represent J by the real matrix B = I plus a
# conjugation flag.
B_REAL = np.eye(8, dtype=np.complex128)


def apply_J(v):
    """Antilinear real structure J(v) = B * conjugate(v) on C^8 (here B = I)."""
    return B_REAL @ np.conjugate(v)


def J_conjugate_operator(A):
    """Return J A J^{-1} as a matrix.

    For J(v) = B conj(v) with B real and B^2 = I (so J^2 = I), one has
    (J A J^{-1})(v) = B conj( A ( B conj(v) ) ) = B conj(A) B v.
    """
    return B_REAL @ np.conjugate(A) @ B_REAL


def epsilon_from_J():
    """epsilon = sign such that J^2 = epsilon * I."""
    # J^2(v) = B conj(B conj(v)) = B B v = B^2 v = I v  (B real, B^2 = I).
    J2 = B_REAL @ np.conjugate(B_REAL)  # = B^2 = I
    sign = 1.0 if np.allclose(J2, np.eye(8)) else (-1.0 if np.allclose(J2, -np.eye(8)) else float("nan"))
    return sign, J2


def build_chirality(gens):
    """gamma = i * L_1 L_2 ... L_6 (volume element of 6 generators)."""
    G6 = [g.astype(np.complex128) for g in gens[:6]]
    prod = np.eye(8, dtype=np.complex128)
    for g in G6:
        prod = prod @ g
    gamma = 1j * prod
    return gamma


def epsilon_pp_from(gamma):
    """epsilon'' such that J gamma J^{-1} = epsilon'' gamma."""
    JgammaJ = J_conjugate_operator(gamma)
    # Solve JgammaJ = s * gamma for scalar s (gamma is invertible).
    # Use a least-squares scalar fit: s = <gamma, JgammaJ> / <gamma, gamma>.
    num = np.vdot(gamma.reshape(-1), JgammaJ.reshape(-1))
    den = np.vdot(gamma.reshape(-1), gamma.reshape(-1))
    s = num / den
    return s, JgammaJ


KO_TABLE = {
    (1.0, 1.0): 0,    # (epsilon, epsilon'')
    (-1.0, -1.0): 2,
    (-1.0, 1.0): 4,
    (1.0, -1.0): 6,
}


def main():
    gens = build_generators()

    print("=" * 78)
    print("  LEVER B — KO-DIMENSION OF THE OCTONIONIC INTERNAL SPACE")
    print("  The single integer that decides chirality-without-doubling.")
    print("=" * 78)

    # 1/2 — Clifford generators
    cliff_ok, cliff_err = check_clifford(gens)
    print("\n  Step 1  Left multiplications L_{e_i} (i=1..7), 8x8 real")
    print(f"      Clifford relations {{L_i,L_j}} = -2 delta_ij : "
          f"{'PASS' if cliff_ok else 'FAIL'}  (max err {cliff_err:.1e})")
    print("      => the L_{e_i} generate Cl(0,7).")

    dimC, irr_ok = check_irreducible_complex(gens)
    print("\n  Step 2  Complexified action on C^8")
    print(f"      dim_C of generated algebra        : {dimC}  "
          f"(M_8(C) has 64)")
    print(f"      irreducible C(8) action           : "
          f"{'PASS' if irr_ok else 'FAIL'}")
    print("      => C (x) O ~ Cl(6) acts irreducibly on C^8 (Furey / "
          "Dubois-Violette).")

    # 3 — real structure
    eps, J2 = epsilon_from_J()
    print("\n  Step 3  Real structure J = complex conjugation")
    print("      (its fixed points are the real octonions O in C (x) O)")
    print(f"      J^2 = epsilon * I  ->  epsilon       : {eps:+.0f}")

    # 4 — chirality grading
    gamma = build_chirality(gens)
    gamma2 = gamma @ gamma
    gamma2_ok = np.allclose(gamma2, np.eye(8))
    eig = np.linalg.eigvalsh((gamma + gamma.conj().T) / 2.0)
    n_plus = int(np.sum(eig > 0))
    n_minus = int(np.sum(eig < 0))
    print("\n  Step 4  Chirality grading gamma = i L_1...L_6 (volume element)")
    print(f"      gamma^2 = +I                         : "
          f"{'PASS' if gamma2_ok else 'FAIL'}")
    print(f"      Weyl split (dim +1 / dim -1)         : {n_plus} / {n_minus}")

    s, _ = epsilon_pp_from(gamma)
    eps_pp = float(np.round(s.real))
    consistent = np.isclose(s.imag, 0.0, atol=1e-9) and abs(abs(s) - 1.0) < 1e-6
    print(f"      J gamma J^-1 = epsilon'' gamma       : "
          f"epsilon'' = {eps_pp:+.0f}  (s = {s.real:+.3f}{s.imag:+.3f}i)")
    if not consistent:
        print("      [warn] epsilon'' fit not a clean +/-1; interpret with care.")

    # 5 — KO-dimension
    ko = KO_TABLE.get((eps, eps_pp), None)
    print("\n  " + "-" * 74)
    print("  RESULT")
    if ko is not None:
        print(f"   * (epsilon, epsilon'') = ({eps:+.0f}, {eps_pp:+.0f})  ->  "
              f"KO-dimension = {ko} (mod 8)")
        if ko == 6:
            print("   * KO-DIMENSION 6 -- the SAME value Connes' noncommutative-geometry")
            print("     Standard Model requires. The octonionic internal space is")
            print("     CHIRAL-CAPABLE: a real structure exists that lets one Weyl half")
            print("     carry the physical fermions WITHOUT a mirror partner. This is")
            print("     exactly the cure for the doubling that downgraded the triality")
            print("     route (three_generations_nogo_audit.py).")
        else:
            print(f"   * KO-DIMENSION {ko} (not 6). On this construction the internal")
            print("     space does NOT sit at the Connes chiral value; the mirror-")
            print("     fermion problem is structural for this real structure and a")
            print("     different J (or a genuine obstruction) must be confronted.")
    else:
        print(f"   * (epsilon, epsilon'') = ({eps:+.0f}, {eps_pp:+.0f}) is not an even-")
        print("     KO-dimension pair; the chosen (J, gamma) do not define a")
        print("     consistent even real spectral triple. Reported honestly.")

    print("\n  SCOPE / KILL CONDITION (recorded)")
    print("   * This fixes the KO-dimension of the INTERNAL Clifford module only.")
    print("     The full CHO spectral triple needs a Dirac operator D (epsilon':")
    print("     J D = epsilon' D J) which is NOT yet specified -- so this is a")
    print("     necessary, not sufficient, chirality result.")
    print("   * KILL: if no choice of D compatible with this (J, gamma) reproduces")
    print("     a chiral, anomaly-free one-generation spectrum, the chirality route")
    print("     is falsified despite the favourable KO-dimension.")
    print("   * Handoff to Lever C (ladder_charges.py): given a chiral half, does")
    print("     the SU(3)xSU(2)xU(1) action assign the CORRECT hypercharges?")
    print()


if __name__ == "__main__":
    main()
