"""
Inverse-spectral experiment — a single algebra-internal Dirac operator.
=======================================================================

The strategic question (from bayesian_evidence.py): ln B ~ -21 favours the
numerology null until ~31 of ~83 prefactor BITS are *derived* rather than
chosen. Grinding one bridge prefactor at a time is slow. The inverse-spectral
bet is to flip the burden of proof: instead of guessing one operator per channel
and paying a bit each time, declare ONE generative object -- a finite Dirac
operator D on the CHO internal space -- and let a Connes-style spectral action
emit relations with ZERO per-channel knobs.

This module is the smallest honest go/no-go for that bet. It does NOT assume the
answer; it COUNTS.

The experiment
--------------
A finite spectral triple (A, H, D; J, gamma) encodes physics in D:
  * eigenvalues of D            -> fermion masses (Yukawa x vev),
  * Tr f(D/Lambda) heat coeffs  -> cosmological term, Einstein-Hilbert,
                                   Yang-Mills + Higgs potential.
The famous open problem in Connes' Standard Model is that the Yukawa entries of
D are FREE inputs: the geometry fixes which entries may be nonzero (via the
order-zero, order-one and real-structure axioms) but not their magnitudes.

The CHO-specific bet tested here: if D is forced to be *algebra-internal* --
built only from left/right octonion multiplications, i.e. an element of the
algebra acting on its own module rather than an arbitrary Hermitian matrix --
does that collapse the free parameters enough to FORCE the spectrum (mass
ratios) instead of leaving them free?

We answer this by direct construction on the one-generation module C (x) O = C^8
(the same module ladder_charges.py and ko_dimension_chirality.py use):

  1. Build the grading gamma (KO-dim-6 volume element) and real structure J.
  2. Build the FULL operator algebra generated by left- and right-octonion
     multiplications (the algebra-internal operators).
  3. Count the dimension of the space of admissible Dirac operators
        D = D^dagger,  D gamma = - gamma D,  D J = + J D,
     in TWO regimes:
        (a) GENERIC: any Hermitian matrix obeying the axioms   (the Connes count)
        (b) INTERNAL: additionally D lies in the octonion operator algebra
     The drop from (a) to (b) is the number of bits the CHO restriction buys.
  4. Sample admissible internal D's and inspect the SPECTRUM: is it rigid
     (fixed eigenvalue ratios -> mass ratios derived) or free?
  5. Print a strict KNOBS-IN vs CONSTANTS-OUT verdict. A derivation requires
     constants_out > knobs_in. Anything else is re-parametrisation, and we say so.

The expected honest outcome is a NEGATIVE that is itself informative: one
generation of algebra-internal D is too rigid (octonion left-multiplications are
isospectral, eigenvalues +-i) to carry a hierarchy, which is precisely why the
framework needs the 432 = 16 x 27 = A_Weyl x J3(O) space across generations. A
clean negative here MOTIVATES the larger space rather than fitting it.

No scipy. Uses octonion_toolkit.OCT_MULT and numpy.

Run:
    PYTHONDONTWRITEBYTECODE=1 python3 compute/spectral_action.py
"""

import numpy as np

from octonion_toolkit import OCT_MULT


# --------------------------------------------------------------------------
# Octonion multiplication matrices on the real 8-dim module (then complexify).
# --------------------------------------------------------------------------
def left_mult_matrix(i):
    """8x8 real matrix of x -> e_i * x.  (L_i)_{k,j} = OCT_MULT[i, j, k]."""
    L = np.zeros((8, 8))
    for j in range(8):
        for k in range(8):
            L[k, j] = OCT_MULT[i, j, k]
    return L


def right_mult_matrix(i):
    """8x8 real matrix of x -> x * e_i.  (R_i)_{k,j} = OCT_MULT[j, i, k]."""
    R = np.zeros((8, 8))
    for j in range(8):
        for k in range(8):
            R[k, j] = OCT_MULT[j, i, k]
    return R


def operator_algebra_basis():
    """A spanning set of the associative operator algebra generated by left and
    right octonion multiplications on C^8.

    Octonions are non-associative, so left and right multiplications do NOT
    coincide and their products generate a large associative matrix algebra. We
    take {I} together with L_i, R_i (i=1..7) and the second-order products
    L_i L_j, L_i R_j, R_i R_j, then orthonormalise to get an honest dimension
    count of the algebra-internal operators reachable at order <= 2.

    Returns a list of independent 8x8 complex matrices (an orthonormal basis in
    the Hilbert-Schmidt inner product).
    """
    gens = [np.eye(8, dtype=complex)]
    Ls = [left_mult_matrix(i).astype(complex) for i in range(1, 8)]
    Rs = [right_mult_matrix(i).astype(complex) for i in range(1, 8)]
    gens += Ls + Rs
    # second-order products (the non-associativity makes these genuinely new)
    for A in Ls:
        for B in Ls:
            gens.append(A @ B)
    for A in Ls:
        for B in Rs:
            gens.append(A @ B)
    for A in Rs:
        for B in Rs:
            gens.append(A @ B)
    # also allow multiplication by the complex unit i (C (x) O), i.e. i * each gen
    gens = gens + [1j * g for g in gens]
    return orthonormal_independent(gens)


def orthonormal_independent(mats):
    """Gram-Schmidt in the Hilbert-Schmidt inner product <A,B> = Tr(A^dag B).
    Returns an orthonormal basis spanning the same space; drops dependents.
    """
    basis = []
    for M in mats:
        V = M.copy()
        for B in basis:
            V = V - hs_inner(B, V) * B
        nrm = np.sqrt(hs_inner(V, V).real)
        if nrm > 1e-9:
            basis.append(V / nrm)
    return basis


def hs_inner(A, B):
    """Hilbert-Schmidt inner product Tr(A^dag B)."""
    return np.trace(A.conj().T @ B)


# --------------------------------------------------------------------------
# Grading gamma (KO-dim-6 volume element) and real structure J on C^8.
# --------------------------------------------------------------------------
def grading_gamma():
    """gamma = i * L_1 L_2 ... L_6  (chirality operator, gamma^2 = +1).

    Same construction as ko_dimension_chirality.py: the volume element of the
    first six Clifford generators splits C^8 into two Weyl halves (4 + 4).
    """
    g = np.eye(8, dtype=complex)
    for i in range(1, 7):
        g = g @ left_mult_matrix(i).astype(complex)
    g = 1j * g
    return g


def real_structure_conj(v):
    """Real structure J = complex conjugation (the KO-dim-6 choice that gave
    epsilon = +1 in ko_dimension_chirality.py). Acts antilinearly: J v = conj(v).
    """
    return np.conjugate(v)


# --------------------------------------------------------------------------
# Admissible Dirac operators.
# --------------------------------------------------------------------------
def admissible_generic_count(gamma):
    """Dimension of the real vector space of Hermitian D on C^8 with
        D = D^dag  and  D gamma = - gamma D   (odd / off-diagonal in chirality).

    For gamma with eigenvalues +-1 in equal 4/4 split, D is block-off-diagonal:
        D = [[0, Y],[Y^dag, 0]]  with Y an arbitrary 4x4 complex matrix.
    Real dimension = 2 * 4 * 4 = 32 free real parameters. We compute it directly
    from gamma rather than asserting it.
    """
    # projectors onto gamma = +1 / -1 eigenspaces
    P_plus = (np.eye(8) + gamma) / 2
    P_minus = (np.eye(8) - gamma) / 2
    r_plus = int(round(np.trace(P_plus).real))
    r_minus = int(round(np.trace(P_minus).real))
    # off-diagonal Hermitian block Y is r_plus x r_minus complex -> 2*r_plus*r_minus real
    return 2 * r_plus * r_minus, (r_plus, r_minus)


def admissible_internal_basis(gamma, algebra_basis):
    """Basis of Hermitian, chirality-odd operators that ALSO lie in the
    algebra-internal operator algebra.

    We project the admissibility constraints onto the algebra: for each algebra
    basis element g form its Hermitian, gamma-odd part
        D_g = (g + g^dag)/2,   then   D_g^odd = (D_g - gamma D_g gamma)/2,
    collect the D_g^odd and return an orthonormal independent set. Its size is
    the number of algebra-internal admissible Dirac directions = the honest knob
    count for an internal D.
    """
    candidates = []
    for g in algebra_basis:
        herm = (g + g.conj().T) / 2
        odd = (herm - gamma @ herm @ gamma) / 2
        candidates.append(odd)
    return orthonormal_independent(candidates)


def random_internal_dirac(internal_basis, rng):
    """A random admissible internal Dirac operator: real combination of the
    internal admissible basis (kept Hermitian by construction)."""
    D = np.zeros((8, 8), dtype=complex)
    for B in internal_basis:
        c = rng.standard_normal()
        D = D + c * B
    # symmetrise numerically
    return (D + D.conj().T) / 2


def spectrum_ratios(D):
    """Sorted positive singular-value-like spectrum (|eigenvalues|) and the
    ratios to the largest. For a chirality-odd Hermitian D the eigenvalues come
    in +-pairs; we report the distinct magnitudes (the physical masses)."""
    ev = np.linalg.eigvalsh(D)
    mags = np.sort(np.abs(ev))[::-1]
    # collapse +-pairs: take every other after sorting magnitudes
    distinct = []
    for m in mags:
        if not distinct or abs(distinct[-1] - m) > 1e-9 * max(1.0, m):
            distinct.append(m)
    distinct = np.array(distinct)
    top = distinct[0] if distinct.size and distinct[0] > 1e-12 else 1.0
    return distinct, distinct / top


def spectral_rigidity(internal_basis, n_samples=400, seed=0):
    """Sample admissible internal D's and measure how much the eigenvalue RATIOS
    move. If the ratios are pinned (std ~ 0), the spectrum is forced -> mass
    ratios would be DERIVED. If they roam freely, the magnitudes are free knobs.
    Returns (mean_ratios, std_ratios, n_distinct_levels)."""
    rng = np.random.default_rng(seed)
    ratio_samples = []
    n_levels = []
    for _ in range(n_samples):
        D = random_internal_dirac(internal_basis, rng)
        distinct, ratios = spectrum_ratios(D)
        n_levels.append(len(distinct))
        ratio_samples.append(ratios)
    # align by the most common number of levels
    from collections import Counter
    common = Counter(n_levels).most_common(1)[0][0]
    aligned = np.array([r for r in ratio_samples if len(r) == common])
    mean_r = aligned.mean(axis=0) if aligned.size else np.array([1.0])
    std_r = aligned.std(axis=0) if aligned.size else np.array([0.0])
    return mean_r, std_r, common


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------
def main():
    print("=" * 74)
    print("INVERSE-SPECTRAL EXPERIMENT: one algebra-internal Dirac operator")
    print("=" * 74)
    print()
    print("Module: C (x) O = C^8 (one generation, one chirality sector).")
    print("Axioms imposed on D: Hermitian, chirality-odd (D gamma = -gamma D).")
    print()

    gamma = grading_gamma()
    g2 = gamma @ gamma
    print("[1] Grading gamma = i L_1...L_6")
    print("    gamma^2 = I ?            ", np.allclose(g2, np.eye(8)))
    P_plus = (np.eye(8) + gamma) / 2
    split = int(round(np.trace(P_plus).real))
    print("    Weyl split (dim gamma=+1):", split, "+", 8 - split)
    print()

    generic_knobs, (rp, rm) = admissible_generic_count(gamma)
    print("[2] GENERIC admissible Dirac operators (the Connes count)")
    print("    Off-diagonal block Y is", rp, "x", rm, "complex")
    print("    free real parameters (knobs_in, generic):", generic_knobs)
    print()

    alg = operator_algebra_basis()
    print("[3] Algebra-internal operator algebra (left/right octonion mult,")
    print("    order <= 2, over C)")
    print("    dim of internal operator algebra:", len(alg), "of 128 (= dim M_8(C) over R/2... )")
    internal_basis = admissible_internal_basis(gamma, alg)
    internal_knobs = len(internal_basis)
    print("    admissible INTERNAL Dirac directions (knobs_in, internal):",
          internal_knobs)
    bits_bought = 0.0
    if internal_knobs > 0:
        bits_bought = np.log2(max(generic_knobs, 1) / internal_knobs)
    print("    restriction buys log2(generic/internal) =",
          round(bits_bought, 2), "bits of constraint")
    print()

    print("[4] Spectral rigidity of admissible internal D (400 random samples)")
    if internal_knobs == 0:
        print("    no admissible internal Dirac direction exists.")
        mean_r = np.array([1.0])
        std_r = np.array([0.0])
        levels = 1
    else:
        mean_r, std_r, levels = spectral_rigidity(internal_basis)
        print("    distinct mass levels (most common):", levels)
        print("    mean eigenvalue ratios (to largest):",
              np.array2string(mean_r, precision=3, suppress_small=True))
        print("    std  of those ratios over samples  :",
              np.array2string(std_r, precision=3, suppress_small=True))
        rigid = bool(np.all(std_r < 1e-3))
        print("    spectrum RIGID (ratios pinned)?     ", rigid)
    print()

    # ---- strict verdict -------------------------------------------------
    # constants_out = number of *independent* forced mass ratios the spectrum
    # supplies on its own. A ratio counts as forced only if its sample std is
    # negligible AND it is not trivially 1.
    if internal_knobs > 0 and std_r.size:
        forced = [(m, s) for m, s in zip(mean_r, std_r)
                  if s < 1e-3 and abs(m - 1.0) > 1e-6 and m > 1e-9]
        constants_out = len(forced)
    else:
        constants_out = 0

    print("[5] VERDICT  (a derivation requires constants_out > knobs_in)")
    print("    knobs_in (internal admissible D parameters):", internal_knobs)
    print("    constants_out (forced, non-trivial mass ratios):", constants_out)
    if constants_out > internal_knobs:
        verdict = "DERIVATION: spectrum supplies more relations than knobs."
    elif internal_knobs == 0:
        verdict = ("NEGATIVE (structural): no algebra-internal chirality-odd D "
                   "exists on one generation -> the Yukawa cannot be algebra-"
                   "internal here; it must live in the cross-generation 16x27 "
                   "space. This MOTIVATES 432 = A_Weyl x J3(O).")
    elif constants_out == 0:
        verdict = ("NEGATIVE (rigid-but-empty / free): internal D's spectrum "
                   "carries no forced non-trivial ratio -> one generation cannot "
                   "produce a mass hierarchy. Re-parametrisation, not derivation. "
                   "MOTIVATES the cross-generation 432 space.")
    else:
        verdict = ("PARTIAL: some forced ratios, but knobs_in >= constants_out "
                   "-> not yet a net derivation; report as residual inputs.")
    print()
    print("    -> " + verdict)
    print()
    print("=" * 74)
    print("HONEST READING")
    print("-" * 74)
    print("This is the smallest go/no-go for the inverse-spectral pivot. A clean")
    print("negative at one generation is the EXPECTED and USEFUL result: it shows")
    print("the mass hierarchy cannot be an artefact of a single-generation D and")
    print("must come from the cross-generation 16x27 = A_Weyl x J3(O) structure,")
    print("turning the 432-space from a fitted choice into a forced requirement.")
    print("Next step (separate module): repeat the count on the full 432 space")
    print("with J3(O) triality acting across the three idempotents and ask the")
    print("same knobs_in vs constants_out question there.")
    print("=" * 74)

    return {
        "generic_knobs": generic_knobs,
        "internal_knobs": internal_knobs,
        "bits_bought": float(bits_bought),
        "constants_out": constants_out,
        "verdict": verdict,
    }


if __name__ == "__main__":
    main()
